### ISSUE TITLE
🐁 Mouse Support in LineReader does not work as documented on x3 different Terminals on Linux

### ISSUE THREAD

**Issue by vorburger** [jline/jline3#1254]
In https://github.com/enola-dev/enola/pull/1376,

I've attempted to _enable Mouse Support in LineReader,_

as documented on https://jline.org/docs/advanced/mouse-support/#mouse-support-in-linereader.

But when I click between 2 words on a prompt, then it does not reposition the cursor, but prints "garbagge" (ANSI control sequences). 

I've tried this on x3 different Terminals on Linux:

* [Kitty](https://sw.kovidgoyal.net/kitty/) 0.41.1 with [this config](https://github.com/vorburger/vorburger-dotfiles-bin-etc/blob/main/dotfiles/kitty/kitty.conf) (prints `[<0;32;24M[<0;32;24m`)
* [ptyxis](https://gitlab.gnome.org/chergert/ptyxis) 47.13 on Fedora 41 (prints `[<0;32;30M[<0;32;30m`)
* GNOME Terminal of Fedora 41 _(Version 3.54.4 for GNOME 47, using VTE version 0.78.4 +BIDI +GNUTLS +ICU +SYSTEMD)_ (prints `[<0;32;20M[<0;32;20m`)

Is this expected to "just work"? Do Terminals need special configuration for this to work? What could be the cause of seeing this "garbagge"?

**Comment by vorburger** [comment]
I've meanwhile gathered / figured / learned that _"prints garbagge"_ really just means that the (current) `KeyMap` has no `Binding` for the respective ANSI control sequences. 

But what's still less clear to me is if I need to add what seems to be missing here in my code, or if this is expected to "just work", and if so why it does not out of the box (for me).

**Comment by gnodet** [comment]
I've just fixed this issue in Nano yesterday.  If you look at the recent commits, you should find it.
You can use MouseSupport.keys(terminal) to get all prefixes for mouse events.

See https://github.com/jline/jline3/commit/287851d0cff9ecf516193504b486aa2831158e7d

**Comment by vorburger** [comment]
> See https://github.com/jline/jline3/commit/287851d0cff9ecf516193504b486aa2831158e7d

Looks like that made it into 3.30.0 (right?). I indeed filed this issue while I was still on 3.29.0. 

https://github.com/enola-dev/enola/pull/1376 is now rebased, and includes https://github.com/enola-dev/enola/pull/1373 - but I'm still seeing this issue.

> I've just fixed this issue in Nano yesterday. If you look at the recent commits, you should find it. You can use MouseSupport.keys(terminal) to get all prefixes for mouse events.

So, I'm not actually using the `MouseSupport` API at all. In the aforementioned PR, I'm just:

```java
LineReaderBuilder.builder()
    .variable(LineReader.MOUSE, true)
```

The point (for now) is just to enable e.g. clicking between 2 words on a `LineReader` prompt to position the cursor.

Might fixing this still need a similar adjustment to the one you have made in `Nano` and `Tmux` somewhere (?) in `LineReader` or so?

I had a quick look myself, but I don't see any use of `readMouseEvent` in anything `LineReader` related?

Or would one need to do [something like this](https://github.com/jline/jline3/blob/e4722ee8b1b59aa97af48928f8bd624a368a357f/builtins/src/test/java/org/jline/example/Example.java#L411) oneself, for this _("clicking in the input line or using the mouse wheel")_ to actually work? But that's not what https://jline.org/docs/advanced/mouse-support/#mouse-support-in-linereader claims, and what is illustrated in [`LineReaderMouseExample`](https://github.com/jline/jline3/blob/e4722ee8b1b59aa97af48928f8bd624a368a357f/demo/src/main/java/org/jline/demo/examples/LineReaderMouseExample.java#L21) (which I admit I have not actually run; just wrote similar code after looking at it).

**Comment by vorburger** [comment]
> You can use `MouseSupport.keys(terminal)` to get all prefixes for mouse events.

Sorry, I'm stupid; so what would one do with the String[] keys that method returns?

**Comment by gnodet** [comment]
> > You can use `MouseSupport.keys(terminal)` to get all prefixes for mouse events.
> 
> Sorry, I'm stupid; so what would one do with the String[] keys that method returns?

https://github.com/jline/jline3/blob/ed279e107e9fe9874e8a450e673a3d454cdc6fe2/builtins/src/main/java/org/jline/builtins/Nano.java#L2268

and

https://github.com/jline/jline3/blob/ed279e107e9fe9874e8a450e673a3d454cdc6fe2/builtins/src/main/java/org/jline/builtins/Nano.java#L3249

**Comment by gnodet** [comment]
> > See [287851d](https://github.com/jline/jline3/commit/287851d0cff9ecf516193504b486aa2831158e7d)
> 
> Looks like that made it into 3.30.0 (right?). I indeed filed this issue while I was still on 3.29.0.
> 
> [enola-dev/enola#1376](https://github.com/enola-dev/enola/pull/1376) is now rebased, and includes [enola-dev/enola#1373](https://github.com/enola-dev/enola/pull/1373) - but I'm still seeing this issue.
> 
> > I've just fixed this issue in Nano yesterday. If you look at the recent commits, you should find it. You can use MouseSupport.keys(terminal) to get all prefixes for mouse events.
> 
> So, I'm not actually using the `MouseSupport` API at all. In the aforementioned PR, I'm just:
> 
> LineReaderBuilder.builder()
>     .variable(LineReader.MOUSE, true)
> The point (for now) is just to enable e.g. clicking between 2 words on a `LineReader` prompt to position the cursor.
> 
> Might fixing this still need a similar adjustment to the one you have made in `Nano` and `Tmux` somewhere (?) in `LineReader` or so?
> 
> I had a quick look myself, but I don't see any use of `readMouseEvent` in anything `LineReader` related?
> 
> Or would one need to do [something like this](https://github.com/jline/jline3/blob/e4722ee8b1b59aa97af48928f8bd624a368a357f/builtins/src/test/java/org/jline/example/Example.java#L411) oneself, for this _("clicking in the input line or using the mouse wheel")_ to actually work? But that's not what https://jline.org/docs/advanced/mouse-support/#mouse-support-in-linereader claims, and what is illustrated in [`LineReaderMouseExample`](https://github.com/jline/jline3/blob/e4722ee8b1b59aa97af48928f8bd624a368a357f/demo/src/main/java/org/jline/demo/examples/LineReaderMouseExample.java#L21) (which I admit I have not actually run; just wrote similar code after looking at it).

My bad, the `LineReader` has not been adapted with the updates on mouse support. I'll push a PR to fix that asap.

**Comment by gnodet** [comment]
> My bad, the `LineReader` has not been adapted with the updates on mouse support. I'll push a PR to fix that asap.

Raised #1261

**Comment by gnodet** [comment]
> 
> > My bad, the `LineReader` has not been adapted with the updates on mouse support. I'll push a PR to fix that asap.
> 
> Raised #1261 

@vorburger Could you give it a try ?

**Comment by vorburger** [comment]
> @vorburger Could you give it a try ?

Can do! Thank You for the "ping", I was just going to wait for a release... 😺  but yes I sure can try a `SNAPSHOT`, and let you know.

Except that I need to do https://github.com/enola-dev/enola/issues/1383, first...

I don't suppose you're pusing `SNAPSHOT` of this project to any remote repo?

**Comment by vorburger** [comment]
> Except that I need to do https://github.com/enola-dev/enola/issues/1383, first...

No Go / PITA; see https://github.com/bazel-contrib/rules_jvm_external/issues/901 (and its https://github.com/bazel-contrib/rules_jvm_external/pull/974) for why.

> @vorburger Could you give it a try ?

Actually, forget about testing this "downstream" (in my project using it), with #1265, I was able to confirm "upstream" that it works now.

Reverting #1261 I see the same problem, and with #1261 (on `master` as-is) clicking between words on input line works.

I'm therefore now closing this as completed.
